# Generated by Django 4.0.5 on 2022-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='positions',
            field=models.ManyToManyField(to='sales.position'),
        ),
    ]
